version: '3.7'

services:
  nats-srv:
    image: docker.io/bitnami/nats:2
    # expose:
    #   - '4222'
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      USER_SERVICE_DB: postgres://dpmajyjy:E8JDF1mIwV3pEZhduB_jVfYHWWURwcav@fanny.db.elephantsql.com/dpmajyjy
      SECRET_KEY: SECRET_KEY_SECRET_KEY
      NATS_URL: nats://nats-srv:4222
    expose:
      - '8123'
    ports:
      - '8123:5050'
    depends_on:
      - nats-srv

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    environment:
      TXN_SERVICE_DB: postgres://ajxvpnjl:hgCi_TQJsOuJ9LKx7FMp7RAOycI1kHgW@fanny.db.elephantsql.com/ajxvpnjl
      SECRET_KEY: SECRET_KEY_SECRET_KEY
      NATS_URL: nats://nats-srv:4222
    expose:
      - '8124'
    ports:
      - '8124:5060'
    depends_on:
      - nats-srv

  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - '8888'
      - '1337'
    ports:
      - '8888:8888'
      - '1337:1337'

